# Generated by Django 4.0.6 on 2022-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='media/slider/%Y/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
