# Generated by Django 4.0.6 on 2022-07-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
            ],
        ),
    ]
