# Generated by Django 4.0.6 on 2022-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
