# Generated by Django 4.0.6 on 2022-07-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(blank=True, default='https://www.youtube.com', null=True),
        ),
    ]
