# Generated by Django 4.0.6 on 2022-07-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_remove_team_role_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fb_link',
        ),
    ]
